### PR TITLE
Beamline

### PR DESCRIPTION
**Pull request by Elisis**

### CODE REVIEW

**Comment by Elisis** [comment]
Fuck off Spotless

**Comment by Elisis** [comment]
:thunkban: why does it say these were committed 19 days ago

**Comment by Dream-Master** [comment]
> :thunkban: why does it say these were committed 19 days ago

Github is lying :P

btw no more spotless in darft prs. it was disabled

**Comment by Elisis** [comment]
> btw no more spotless in darft prs. it was disabled

Oh nice, that does help a lot

**Comment by Dream-Master** [comment]
@Elisis can you finish this new beamline stuff?

**Comment by Elisis** [comment]
GT updates too fast lol

**Comment by serenibyss** [comment]
Closing as this repo is archived

**Pull request closed without merging**
