### PR TITLE
Add muffler & maintenance requirement to digester & dissolution tank

### PR DESCRIPTION
**Pull request by HoleFish**

### CODE REVIEW

**Comment by Pxx500** [comment]
Is there a reason for that?

**Comment by HoleFish** [comment]
Have heard lots of words like "why would my digester turn off" without realizing they forgot the muffler. Maintenance hatch is not a big deal here and can be changed

**Comment by Pxx500** [comment]
oh so it needs the muffler but it doesn't show it?

**Comment by HoleFish** [comment]
it needs a muffler, it shows the muffler (via https://github.com/GTNewHorizons/GTNH-Lanthanides/pull/84), but it will form without a muffler. it's strange and confusing, this is the reason

**Review by Pxx500 — APPROVED** [review]

**Pull request merged**
