### PR TITLE
Delete unused stuff

### PR DESCRIPTION
**Pull request by Pxx500**
Somewhat continuation of https://github.com/GTNewHorizons/GTNH-Lanthanides/pull/58
Deletes unused stuff, mostly leftovers of already deleted rocket fuel lines

List of deleted fluids items:
image
image
image
image
image

not sure about those (they have no recipes but seem very closely tied to monaline/bastline):
image

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Elisis any objections? Are we need those stuff ?

**Comment by Elisis** [comment]
Other than vanadium pentoxide most of those are from bot fuels, I think. Let me double check

**Comment by Elisis** [comment]
Yeah all of the ones in the top image can be removed, permanganate and chlorate should probably be kept, and the rest can go

**Comment by Pxx500** [comment]
@Elisis done

**Review by Elisis — APPROVED** [review]

**Pull request merged**
