### PR TITLE
Update WerkstoffMaterialPool.java - Fix "Impure Samarium ..." naming

### PR DESCRIPTION
**Pull request by Speecker**
Renamed "Impure Samarium Oxalate" -> "Coarse Samarium Oxalate". Reason: Deny it from entering OreProc Systems utilizing "dustImpure*" filtering to gather any Impure Dust that can be centrifuged - but Impure Samarium Oxalate needs a Chemical Reactor instead !

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Speecker if it is more accurate naming i have nothing against it.

**Comment by Speecker** [comment]
> @Speecker if it is more accurate naming i have nothing against it.

I thought about dustDirtySamarium as well but sure i mean it can be anything else but not dustImpureSamarium as it conflicts with filtering by dustImpure* because it cant be processed by centrifuges :)
What more accurate naming would you suggest then ?
May i edit it to what you prefer as naming instead ?

**Comment by Speecker** [comment]
Or maybe just remove the Impure infront entirely as Sm2(C2O4)3 is just Samarium(III) Oxalate (a salt of samarium) and there is no impure or so and there may be no reason to have an Impure Dust of it if there is no "regular" one ?
Same with Samarium(III)-Chlorid - SmCI3 (not SmC13).
But im no chemist by any means.

**Comment by Elisis** [comment]
Should probably remove the question marks in front of the chemical formulae as well

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
