### PR TITLE
enable the mid chemical recipe in rocket fuel

### PR DESCRIPTION
**Pull request by GlodBlock**
enable the mid product recipe in bot's rocket fuel, since some of them are used in kevlar and lanth line.
the final rocket fuel recipe is still disabled

### CODE REVIEW

**Comment by chochem** [comment]
cant you make the chem plant ones? I was personally hoping we can eventually remove these fluids to final solve all those fluid conversion bugs that they cause with the forge fluid unification due to the duplicate nature.

**Comment by GlodBlock** [comment]
phosgene for example. maybe there are more used in other places since there are a lot of common chemicals here

**Comment by chochem** [comment]
the ones I am thinking of specifically are formaldehyde and hydrogen peroxide. Though there might be more.

**Review by miozune — APPROVED** [review]
Let’s merge this for now

**Pull request merged**
